version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bioplatform_db
      POSTGRES_USER: bioplatform_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bioplatform_user:your_password@db:5432/bioplatform_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://bioplatform_user:your_password@db:5432/bioplatform_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
      - backend

volumes:
  postgres_data:
